server:
  port: 8088

spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2-db/test
    username: test
    password: test
    driverClassName: org.h2.Driver

  data:
    mongodb:
      database: test
      port: 33333
    rest:
      base-path: /api/test

  mongodb:
    embedded:
      version: 4.0.21
      features: NO_HTTP_INTERFACE_ARG
